# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import batch_data_pb2 as batch__data__pb2


class TransferBatchDataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/TransferBatchData/Send',
        request_serializer=batch__data__pb2.BatchData.SerializeToString,
        response_deserializer=batch__data__pb2.ReceiveReply.FromString,
        )


class TransferBatchDataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransferBatchDataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=batch__data__pb2.BatchData.FromString,
          response_serializer=batch__data__pb2.ReceiveReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TransferBatchData', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
